definitions:
  caches:
    npm: .npmcache
pipelines:
  branches:
    master:
      - step:
          name: Build
          image: node:11
          caches:
            - node
            - npm
          script:
            - npm install --cache .npmcache
            - npm run build:prod
          artifacts:
            - build/**
      - step:
          trigger: manual
          name: deploy to prod
          image: atlassian/pipelines-awscli:latest
          deployment: production
          script:
            - aws s3 sync build/ s3://${PD_PROD_S3_BUCKET} --region ${PD_PROD_AWS_S3_REGION} --delete
            - aws cloudfront create-invalidation --distribution-id ${PD_PROD_CLOUDFRONT_ID} --paths "/*"
    develop:
      - step:
          name: Build
          image: node:11
          caches:
            - node
            - npm
          script:
            - npm install --cache .npmcache
            - npm run build:stage
          artifacts:
            - build/**
      - step:
          name: deploy to stage
          image: atlassian/pipelines-awscli:latest
          deployment: staging
          script:
            - aws s3 sync build/ s3://${S3_BUCKET} --region ${AWS_S3_REGION} --delete
            - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"
      - step:
          name: deploy to ec2
          script:
            - mkdir -p ~/.ssh
            - cat known_hosts >> ~/.ssh/known_hosts
            - (umask  077 ; echo ${STAGE_KEY} | base64 --decode > ~/.ssh/id_rsa)
            - scp -r build/* ${STAGE_USER}@{STAGE_SERVER}:${STAGE_DEPLOYMENT_PATH}/.
  pull-requests:
    '**':
      - step:
          name: Build
          image: node:11
          caches:
            - node
            - npm
          script:
            - npm install --cache .npmcache
            - npm run build
