export const generateDefaultText = (creatorName) => ({
  terms: ``,
  refund_policy: `
  <p>I hereby understand and agree that I can only expect to get a refund for the product I am purchasing within the refund period set for each product and shown on the service purchase page.</p>
  
  <p>I can reschedule my session to some other session depending on the availability and fully at the discretion of <strong>${creatorName}</strong> and that I will not ask for a refund if I fail to cancel the service within the stated refund period.<p>
  `,
  waiver: `
  <p>I hereby agree to the following:<p>
<ol>
<li>That I am participating in yoga lessons, classes, workshops, and/or healing arts activities (collectively, the “Activities”) offered by <strong>${creatorName}</strong>. The Activities may be offered in a physical location or online by Zoom, videos, television, podcasts, apps or other digital media or platforms. All of such offerings, either physical or online, shall be considered “Activities.”</li>
<li>I recognize that these Activities require physical exertion, which may be strenuous and may cause physical injury, and I am fully aware of the risks and hazards involved.</li>
<li>I understand that it is my responsibility to consult with a physician prior to and regarding my participation in any of these Activities. I represent and warrant that I am physically fit and I have no medical condition that would prevent my full participation in any of these Activities. I understand that it is my responsibility to consult with a physician before my participation in the Activities. If I have done so, I have taken the physician’s advice. I understand that <strong>${creatorName}</strong> reserves the right to refuse my participation in any Activity on medical, fitness or any other grounds. If I have any of the Risk Factors (as defined below) for increased risk of coronavirus infection (COVID-19), I will consult with a physician before I participate in any Activities at any physical location and will follow the physician’s advice.</li>
<li>I am aware that my participation in the Activities could result in high blood pressure, fainting, heartbeat disorders, physical injury, heart attack or stroke and may aggravate pre-existing injuries. I understand that I could experience muscle, back, neck and other injuries as a result of my participation in the Activities. I understand my physical limitations and I am sufficiently self-aware to stop my participation in any Activity before I become injured or aggravate a pre-existing injury. I am aware that my participation in the Activities at a physical location could result in exposure to COVID-19. I am aware that, if I am over the age of 65 or have an underlying medical problem (such as asthma, chronic kidney or lung disease, diabetes, hemoglobin disorders, immunocompromised or with significant liver disease, heart conditions, obesity or pregnancy) (collectively, “Risk Factors”), I have an increased risk of contracting serious medical issues or potential death if I am exposed to COVID-19.</li>
<li>In consideration of being permitted to participate in the Activities, I agree to assume full responsibility for any risks, injuries or damages, known or unknown, including exposure to COVID-19 and potentially serious medical issues or death, that I might incur as a result of participating in the Activities in a physical location or online, including those which may result from the negligence of that location.</li>
<li>I acknowledge that COVID-19 infections have been confirmed in every state in the United States and throughout the world. In accordance with the guidance and protocols issued by the Centers for Disease Control and Prevention, the State of New York Department of Health (collectively, the “Health Authorities”) for slowing the transmission of COVID-19, I hereby agree, represent, and warrant that I shall not visit or utilize the facilities, services, and programs of the physical location within fourteen (14) days after:<ul> <li>returning from any areas subject to a CDC Level 3 Travel Health Notice,</li> <li>exposure to any person returning from any areas subject to a CDC Level 3 Travel Health Notice, or</li> <li>exposure to any person who has a suspected or confirmed case of COVID-19.</li></ul> <br> <br> I further agree that I shall not visit or utilize the facilities, services, and programs of the physical location if I: <ul><li> experience any symptoms of COVID-19, including, without limitation, fever, cough or shortness of breath</li> <li>have a suspected or diagnosed or confirmed case of COVID-19 or</li> <li>believe that I have been exposed to COVID-19.</li></ul> I agree to notify <strong>${creatorName}</strong> immediately if I believe that I have been exposed to COVID-19, have been diagnosed as having COVID-19 or if I experience any of the symptoms of exposure to COVID-19 as described above.</li>
<li>I acknowledge that there is a risk that I may be exposed to COVID-19 if I participate in any Activities in a physical location. I acknowledge that such participation may result in exposure to COVID-19, which could result in quarantine requirements, serious illness, disability, and/or death. I acknowledge that <strong>${creatorName}</strong> is not responsible if I become exposed to COVID-19 while participating in such Activities in a physical location. I therefore assume the full risk and responsibility for any harm that may result if I am exposed to COVID-19 by participating in any such Activities at this location.</li>
<li>In further consideration of being permitted to participate in the Activities (either online or at the physical facilities), I knowingly, voluntarily and expressly waive any “Claim” (as defined below) I may have against <strong>${creatorName}</strong> (a “Released Party”) that I may sustain as a result of participating in the Activities (either online or at the physical facilities) even if the Claim arises from the negligence of any Released Party or anyone else. I agree to indemnify and hold harmless the Released Party from any loss, cost, or liability incurred in defending any Claim made by me or anyone making a Claim on my behalf, even if the Claim is alleged to or did result from the negligence of any Released Party or anyone else. “Claim” includes but is not limited to any and all liabilities, claims, demands, expenses, fees, legal actions, rights of actions for damages, personal injury, mental suffering and distress, illness or death that I may suffer, my spouse, children or unborn child may suffer (including any legal fees or expenses) in connection with participation in any Activity (either online or at the physical facilities) or exposure to COVID-19 as a result of participating in any Activity.</li>
<li>In consideration of being permitted to participate in the Activities I agree to use any studio props ONLY UNDER SUPERVISION and with the permission of <strong>${creatorName}</strong> as directed.</li>
<li>I hereby understand that <strong>${creatorName}</strong> from time to time may photograph, video, or otherwise record classes or events occurring in a physical location or online. I hereby consent to these recordings.</li>
<li>In further consideration of being permitted to participate in the Activities, I knowingly, voluntarily and expressly waive any claim I may have against <strong>${creatorName}</strong> .</li>
<li>I, my heirs or legal representatives forever release, waive, discharge and covenant not to sue <strong>${creatorName}</strong> for any injury or death caused by her negligence or other acts. I have read the above release and waiver of liability and fully understand its contents. I voluntarily agree to the terms and conditions stated above.</li>
</ol>`,
});
