export const headerTemplate = {
  html: `<div><div class="simple-container"><div class="compact-fixed-container"><header class="header-container"><div class="header-brand"><h1 class="brand-text">My Brand</h1></div><SignInButton target="current" buttonType="primary"></SignInButton></header></div></div></div>`,
  css: `* { box-sizing: border-box; } body {margin: 0;}.header-brand{flex-grow:1;flex-shrink:1;flex-basis:auto;padding-top:8px;padding-right:8px;padding-bottom:8px;padding-left:8px;}.header-brand .brand-text{font-size:20px;font-weight:500;margin-bottom:0px !important;}.header-brand .brand-image{max-height:48px;}.header-container{display:flex;flex-grow:0;flex-shrink:1;flex-basis:auto;flex-wrap:nowrap;column-gap:12px;width:100%;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:12px;padding-right:12px;padding-bottom:12px;padding-left:12px;height:64px;align-items:center;}.compact-fixed-container{display:flex;flex-direction:column;justify-content:center;margin-top:0px;margin-right:auto;margin-bottom:0px;margin-left:auto;max-width:980px;width:100%;padding-top:4px;padding-right:4px;padding-bottom:4px;padding-left:4px;}.simple-container{display:block;padding-top:4px;padding-right:4px;padding-bottom:4px;padding-left:4px;width:100%;}`,
  components: `[{"type":"passion-header-block","components":[{"type":"container","removable":false,"draggable":false,"droppable":false,"badgable":false,"stylable":false,"highlightable":false,"copyable":false,"layerable":false,"selectable":false,"hoverable":false,"classes":["simple-container"],"attributes":{},"components":[{"type":"compact-fixed-width-container","removable":false,"draggable":false,"droppable":false,"badgable":false,"stylable":false,"highlightable":false,"copyable":false,"layerable":false,"selectable":false,"hoverable":false,"classes":["compact-fixed-container"],"attributes":{},"components":[{"type":"navbar-header","classes":["header-container"],"attributes":{},"components":[{"type":"header-brand","classes":["header-brand"],"attributes":{},"components":[{"type":"header-text-brand","classes":["brand-text"],"attributes":{}}]},{"type":"SignInButton","layerable":true,"attributes":{"target":"current","buttonType":"primary"}}]}]}]}]}]`,
  styles: `[{"selectors":["header-brand"],"style":{"flex-grow":"1","flex-shrink":"1","flex-basis":"auto","padding-top":"8px","padding-right":"8px","padding-bottom":"8px","padding-left":"8px"},"group":"cmp:header-brand"},{"selectors":[],"selectorsAdd":".header-brand .brand-text","style":{"font-size":"20px","font-weight":"500","margin-bottom":"0px !important"},"group":"cmp:header-brand"},{"selectors":[],"selectorsAdd":".header-brand .brand-image","style":{"max-height":"48px"},"group":"cmp:header-brand"},{"selectors":["header-container"],"style":{"display":"flex","flex-grow":"0","flex-shrink":"1","flex-basis":"auto","flex-wrap":"nowrap","column-gap":"12px","width":"100%","margin-top":"0px","margin-right":"0px","margin-bottom":"0px","margin-left":"0px","padding-top":"12px","padding-right":"12px","padding-bottom":"12px","padding-left":"12px","height":"64px","align-items":"center"},"group":"cmp:navbar-header"},{"selectors":["compact-fixed-container"],"style":{"display":"flex","flex-direction":"column","justify-content":"center","margin-top":"0px","margin-right":"auto","margin-bottom":"0px","margin-left":"auto","max-width":"980px","width":"100%","padding-top":"4px","padding-right":"4px","padding-bottom":"4px","padding-left":"4px"},"group":"cmp:compact-fixed-width-container"},{"selectors":["simple-container"],"style":{"display":"block","padding-top":"4px","padding-right":"4px","padding-bottom":"4px","padding-left":"4px","width":"100%"},"group":"cmp:container"}]`,
};

export const footerTemplate = {
  html: `<PassionFooter></PassionFooter>`,
  css: `* { box-sizing: border-box; } body {margin: 0;}`,
  components: `[{"type":"PassionFooter"}]`,
  styles: `[]`,
};

export const blankPageTemplate = {
  external_id: 'blank',
  name: 'Blank Template',
  description: 'An empty template if you want to start out fresh',
  thumbnail_url: 'none',
  content: {
    components:
      '{"type":"wrapper","stylable":["background","background-color","background-image","background-repeat","background-attachment","background-position","background-size","padding","padding-top","padding-right","padding-bottom","padding-left"],"classes":[{"name":"page-body-section","protected":true}],"attributes":{"id":"i6dr"},"components":[{"type":"simple-text-section-block","classes":["simple-text-section-block"],"attributes":{"layout":"center","id":"id4a"},"components":[{"type":"container","removable":false,"draggable":false,"droppable":false,"badgable":false,"stylable":false,"highlightable":false,"copyable":false,"layerable":false,"selectable":false,"hoverable":false,"classes":["simple-container"],"attributes":{},"components":[{"type":"fixed-width-container","removable":false,"draggable":false,"droppable":false,"badgable":false,"stylable":false,"highlightable":false,"copyable":false,"layerable":false,"selectable":false,"hoverable":false,"classes":["fixed-container"],"attributes":{},"components":[{"type":"simple-text-section","classes":["text-section-container"],"attributes":{},"components":[{"type":"text-section-heading","classes":["text-section-heading"],"attributes":{}},{"type":"text-section-content","classes":["text-section-content"],"attributes":{}}]}]}]}]}],"bg-style":"#ffffff"}',
    styles:
      '[{"selectors":[{"name":"row","private":1}],"style":{"display":"flex","justify-content":"flex-start","align-items":"stretch","flex-wrap":"nowrap","padding-top":"10px","padding-right":"10px","padding-bottom":"10px","padding-left":"10px"}},{"selectors":[{"name":"row","private":1}],"style":{"flex-wrap":"wrap"},"mediaText":"(max-width: 768px)","atRuleType":"media"},{"selectors":[{"name":"cell","private":1}],"style":{"min-height":"75px","flex-grow":"1","flex-basis":"100%"}},{"selectors":["text-section-container"],"style":{"display":"flex","flex-grow":"0","flex-shrink":"1","flex-basis":"auto","width":"100%","padding-top":"8px","padding-right":"8px","padding-bottom":"8px","padding-left":"8px","flex-direction":"column","justify-content":"center","align-items":"center","text-align":"center"},"group":"cmp:simple-text-section"},{"selectors":[],"selectorsAdd":".text-section-container *","style":{"position":"relative","flex-grow":"0","flex-shrink":"0","flex-basis":"auto"},"group":"cmp:simple-text-section"},{"selectors":[],"selectorsAdd":".text-section-container .text-section-heading","style":{"color":"rgb(38, 38, 38)"},"group":"cmp:simple-text-section"},{"selectors":[],"selectorsAdd":".text-section-container .text-section-content","style":{"color":"rgb(72, 73, 73)"},"group":"cmp:simple-text-section"},{"selectors":["fixed-container"],"style":{"display":"flex","flex-direction":"column","justify-content":"center","margin-top":"0px","margin-right":"auto","margin-bottom":"0px","margin-left":"auto","max-width":"980px","width":"100%","min-height":"400px","padding-top":"4px","padding-right":"4px","padding-bottom":"4px","padding-left":"4px"},"group":"cmp:fixed-width-container"},{"selectors":["simple-container"],"style":{"display":"block","padding-top":"4px","padding-right":"4px","padding-bottom":"4px","padding-left":"4px","width":"100%"},"group":"cmp:container"}]',
    html:
      '<div class="page-body-section" id="i6dr"><div layout="center" class="simple-text-section-block" id="id4a"><div class="simple-container"><div class="fixed-container"><div class="text-section-container"><h1 class="text-section-heading">Ad astra per aspera</h1><p class="text-section-content">\n          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque vestibulum vestibulum est at fringilla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed tempus augue vel eros elementum mollis.\n        </p></div></div></div></div></div>',
    css:
      '* { box-sizing: border-box; } body {margin: 0;}.text-section-container{display:flex;flex-grow:0;flex-shrink:1;flex-basis:auto;width:100%;padding-top:8px;padding-right:8px;padding-bottom:8px;padding-left:8px;flex-direction:column;justify-content:center;align-items:center;text-align:center;}.text-section-container *{position:relative;flex-grow:0;flex-shrink:0;flex-basis:auto;}.text-section-container .text-section-heading{color:rgb(38, 38, 38);}.text-section-container .text-section-content{color:rgb(72, 73, 73);}.fixed-container{display:flex;flex-direction:column;justify-content:center;margin-top:0px;margin-right:auto;margin-bottom:0px;margin-left:auto;max-width:980px;width:100%;min-height:400px;padding-top:4px;padding-right:4px;padding-bottom:4px;padding-left:4px;}.simple-container{display:block;padding-top:4px;padding-right:4px;padding-bottom:4px;padding-left:4px;width:100%;}',
  },
};
