export default [
  {
    name: 'Free',
    monthlyPrice: 0,
    monthlyLink: null,
    yearlyPrice: 0,
    yearlyLink: null,
    serviceFee: 12,
    buttonText: 'Get started for FREE',
    inclusiveBanner: null,
    featuresList: [
      'Livestream booking automation',
      'Automate rescheduling, cancellation & refund',
      'Rent one-off videos',
      'Rent video collections & series',
      'Accept international payments',
      'Bi-weekly payouts',
      'Email list builder',
      'Upsell offerings on other offering pages',
      'Get your own passion site',
      'Business growth dashboard',
      'Revenue summary',
      'Email support',
      'Live chat support',
    ],
  },
  {
    name: 'Starter',
    monthlyPrice: 29,
    monthlyLink: 'https://buy.stripe.com/test_28o4kf72a0CbdZC5ko',
    yearlyPrice: 19,
    yearlyLink: 'https://buy.stripe.com/test_8wM6sneuCdoX5t69AF',
    serviceFee: 6,
    buttonText: 'Start 14-day FREE Trial Now',
    inclusiveBanner: 'Everything in FREE Plan, plus',
    featuresList: [
      'Automated email notifications & reminders',
      'Client liability and waiver management',
      'Client management & CRM',
      'Attach PDF/Doc guides to Videos',
      'Give freebie downloads',
      'Email + SMS Marketing',
      'Introductory offers + free trials',
      'Discount Coupons',
      'Gift Cards',
      'Power your existing website with our plugins',
      'Community forum + live events',
      'Onboarding sessions',
    ],
  },
  {
    name: 'Solopreneur',
    monthlyPrice: 89,
    monthlyLink: 'https://buy.stripe.com/test_3csbMHeuCbgPbRueV1',
    yearlyPrice: 59,
    yearlyLink: 'https://buy.stripe.com/test_28o3gb2LU70z6xadQW',
    serviceFee: 3,
    buttonText: 'Start 14-day FREE Trial Now',
    inclusiveBanner: 'Everything in STARTER Plan, plus',
    featuresList: [
      'Daily Payouts',
      'Client feedback + reviews',
      'Showcase testimonials & reviews',
      'Customer referral program',
      'Rank higher with inbuilt SEO',
      'Full data export',
      'Dedicated account manager',
    ],
  },
];
